### ISSUE TITLE
Transitions not working in v10

### ISSUE THREAD

**Issue by mfozz** [p4535992/foundryvtt-scene-transitions#17]
After setting up a transition, it just doesn't work.

- I'm testing the module in v10.291 in the most recent version of the Electron app.
- I'm testing in a new world (D&D 5e 2.1.5) with no other modules enabled other than the support modules (libWrapper and socketlib).
- I can set up a transition with no apparent issues. 
- After setting up a transition, I click "Play Transition" and see the "Loading" notification at the top, but nothing happens.

**Comment by JusticeTheAwesome** [comment]
Same issue here.

**Comment by p4535992** [comment]
click f12 and tell me if you see any red messages

**Comment by mfozz** [comment]
<img width="624" alt="Screenshot 2023-03-01 at 4 38 07 PM" src="https://user-images.githubusercontent.com/89781047/222281607-870ec371-a7a9-49e2-8260-6df2aa889a71.png">

**Comment by p4535992** [comment]
It was a strange issue, not sure if i solved, but try out 0.4.12 , if the issue persist the only option is socketlib is not installed, make sure to have the latest version

**Comment by mfozz** [comment]
Thanks for looking into it again. It’s unfortunately still not working for me. I tried it in Chrome and the electron app. 

Socketlib = 1.0.12
Scene Transitions = 0.4.12
Foundry = 10.291
DnD5e = 2.1.5
Chrome = 110.0.5481.177

<img width="376" alt="Screenshot 2023-03-04 at 11 39 42 AM" src="https://user-images.githubusercontent.com/89781047/222921258-811c5791-649f-4c66-a0be-a8ca484f9daf.png">

**Comment by p4535992** [comment]
Can't replicate...
the only reason you may have that error is for not having installed and/or activated socketlib (the socketLib variable is undefined), but from what you tell me and wrote you should have...

**Comment by mfozz** [comment]
Sigh, yeah. I even tried reinstalling socketlib just now, and it's still not working. I'll keep testing it.

**Comment by p4535992** [comment]
@mfozz did you have by any chance some security addon on the browser or similar ? some antivirus can be annoying sometime.

**Comment by mfozz** [comment]
No it’s doing the same for me in the Electron app- On Mar 6, 2023, at 7:19 AM, 4535992 ***@***.***> wrote:﻿
@mfozz did you have by any chance some security addon on the browser or similar ? some antivirus can be annoying sometime.

**Comment by Indus101** [comment]
Same issue here.

**Comment by mfozz** [comment]
So I'm not getting the same error anymore, but now I see a new line in the console log:
"scene-transitions | Option 'gmHide' is true and you are a GM so you don't see the transition"
I can't find any setting for this, and it always showed me the transition as a GM in v9.

**Comment by haroldnorton** [comment]
Same problem as mfozz.  Fresh install of foundry with  just this and the dependencies, all patched up, and I see the same as a gm.  Just a quick progress bar and no transition.  Tried connecting to it with a session in a browser as a player, and they don't see the transition either.

**Comment by Indus101** [comment]
I was able to get it semi-working by switching the settings as mfozz suggested. However, it behaves inconsistently. Sometimes it plays the transition, sometimes it does the progress bar with no transition. Sometimes it gets "stuck" on a previous transition for a different scene and plays it over and over instead of the current one. 

I did enable debugging and looked in the console for errors to be more helpful, but I'm not very technical and may have been looking in the wrong area. I didn't see any red text, but again, I might not know the right place to look for it.

Just want to say, this module is great and thanks for support / maintaining it. It consistently gets the most "wows" from my players and brings immersion in Foundry VTT to a whole new level. I use it it almost exclusively for mp4 or webm video transitions I make myself in AfterFX, and it's very cinematic.

Thank you.

**Comment by Indus101** [comment]
<message about audio problem deleted as it was a setting i'd missed>

**Comment by Medianoche** [comment]
From my testings, on a FRESH installation:
**CORE: FoundryVTT (Win x64) v10.291
SYSTEM: DnD5e -Fifth Edition System v2.1.5
Module: Scene Transitions v0.4.12
Module: socketlib v1.0.12
Module: libWrapper v1.12.12.0**

I created TWO Scenes. I assigned each of them a different video file, being one .mp4 and the other .webm.

Scene configuration was left only with the "Skippable" flag enabled and the proper "Delay" for each video's duration.

I realized that the FIRST TIME that I tried to PLAY the Transition the CANVAS would not show the video, but the sound included on the file could be heard.
Also, when I clicked to play any transition, the SAME transition I tried first would start showing the VIDEO in the CANVAS, sometimes with twice the audio.

Once the Transition completes if I try to play a different transition, it will show the VIDEO from the new transition but the audio from the previous one will be heard once again.

Also skipping the VIDEO, even if running the same transition, sometimes does not stop the embedded audio.

Finally, If you complete a transition without audio, you can run it again without problems if you "Play Transition again".

BUT if you EDIT your Transition it will play (even if the "Preview" Flag is deactivated. 
And some times you will get the console message: 
`scene-transitions | The scene is not been activated because isGm=true,isPreview=true`

The technology behind the module WORKS, but there is something handling the rendering part incorrectly (but not the rendering in itself, since it sometimes works)

**Comment by joharr79** [comment]
My assumption in how this module works is you create a transition, you click play transition, and it plays the transition before activating that scene. As a GM, you click play and nothing appears to happen. I logged in to a test account in incognito mode as a player and tried. The scene transition does play for the player, but after the transition nothing else happens. Is this how it's supposed to work or should it be activating the scene? Also the audio seems to be broken.

**Comment by ParadoxModule** [comment]
For some reason scenes aren't playing for me, but only for my players. And scene doesn't start properly for them for first few tries
Also, I recieved this error message
"module "scene-transitions" uses pack.private which has been replaced with pack.ownership"
